services:
  - type: web
    name: scrapsail-backend
    env: docker
    plan: free
    region: singapore
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: MYSQL_URL
        value: "jdbc:mysql://scrapsaildb-scrapsaildb.e.aivencloud.com:22902/defaultdb?sslMode=REQUIRED"
      - key: DB_USERNAME
        value: "avnadmin"
      - key: DB_PASSWORD
        value: "AVNS_q3bA1ATbxyymPpRXPIY"
