services:
  - type: web
    name: scrapsail-backend
    env: docker
    plan: free
    region: singapore
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: MYSQL_URL
        value: jdbc:mysql://scrapsaildb-scrapsaildb.e.aivencloud.com:22902/defaultdb?sslMode=REQUIRED
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        value: AVNS_q3bA1ATbxyymPpRXPIY
      - key: SERVER_PORT
        value: 8080
      - key: PORT
        value: 8080
    branch: main
